name: Build and Release Latest

on:
  push:
    branches:
      - main
    paths:
      - '**.typ'
      - 'images/**'
      - 'build.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date_now=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT

      - name: Install system dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm typst typstyle ghostscript git

      - name: Run Build Script
        run: |
          chmod +x build.sh
          ./build.sh --ci

      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Последняя сборка (${{ steps.date.outputs.date_now }})"
          body: |
            ### 🚀 Автоматическая сборка проекта
            Это актуальная версия цифрового издания книги. 

            **Что нового:**
            - Автоматическая компиляция из Typst-исходников.
            - Оптимизация размера PDF (сжатие изображений без потери читаемости).
            - Обновление структуры.

            **Файлы:**
            - `book.pdf` — основная книга для чтения.
          files: book.pdf
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
